import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import {
  authed,
  createTestContext,
  hasDatabase,
  registerActor,
  type Actor,
  type TestContext,
} from './helpers.js';

/**
 * Tenant exposure across a portfolio.
 *
 * The interesting arithmetic — what a lease's rent and occupied area actually
 * are — already belongs to the engine and is tested there. What is specific
 * here is the roll-up across properties, and one thing easy to get wrong in
 * exactly the way that matters most: a `leaseCashFlows` row generated by the
 * engine's own rollover simulation is not always a real tenant.
 *
 * A `renewal` branch carries the real tenant's own id — it is that tenant,
 * weighted by their probability of staying, and belongs in their exposure. A
 * `new_lease` branch is the engine's placeholder for whoever eventually
 * re-lets the space; `leases.ts` gives it a synthetic tenant id
 * (`market:<profileId>`) that matches no row in `tenants`. Counting it as
 * exposure would attribute rent to a name nobody signed for, and — before
 * this was fixed — asking the database to look up that id as a tenant threw
 * an invalid-uuid error rather than quietly returning nothing.
 */
describe.skipIf(!hasDatabase)('tenant exposure across a portfolio', () => {
  let ctx: TestContext;
  let owner: Actor;
  let propertyA: string;
  let propertyB: string;
  let anchorTenantId: string;
  let anchorTenantName: string;
  let portfolioId: string;

  beforeAll(async () => {
    ctx = await createTestContext();
    owner = await registerActor(
      ctx.app,
      'tenant-exposure@example.invalid',
      'Tenant Exposure Owner',
    );
    await request('POST', '/api/v1/organizations', owner.cookie, { name: 'Fennimore Capital' });

    propertyA = await createProperty('Fennimore Plaza', '50000');
    propertyB = await createProperty('Fennimore Annex', '30000');

    // A tenant occupying space in both properties, so the portfolio total is
    // more than either property alone would report — the whole reason this
    // roll-up exists.
    const tenant = await request('POST', '/api/v1/tenants', owner.cookie, {
      name: 'Kestrel Analytics Inc.',
    });
    anchorTenantId = (tenant.json() as { tenant: { id: string } }).tenant.id;
    anchorTenantName = 'Kestrel Analytics Inc.';

    const modelA = await createModel(propertyA);
    await addSpace(propertyA, 'WHOLE', '50000');
    await addLease(modelA, 'L-A1', anchorTenantId, '50000', 'WHOLE', {
      commencementDate: '2026-01-01',
      expirationDate: '2035-12-31',
      baseRent: '30.00',
    });
    await calculateModel(modelA);

    const modelB = await createModel(propertyB);
    await addSpace(propertyB, 'WHOLE', '30000');
    await addLease(modelB, 'L-B1', anchorTenantId, '30000', 'WHOLE', {
      commencementDate: '2026-01-01',
      expirationDate: '2035-12-31',
      baseRent: '25.00',
    });
    await calculateModel(modelB);

    portfolioId = await createPortfolio('Fennimore Fund I', [propertyA, propertyB]);
  }, 90_000);

  afterAll(async () => {
    await ctx?.close();
  });

  /* ---------------------------------------------------------------------- */

  async function request(
    method: 'GET' | 'POST' | 'PUT',
    url: string,
    cookie: string,
    payload?: unknown,
  ) {
    const response = await ctx.app.inject({
      method,
      url,
      headers: authed(cookie),
      ...(payload !== undefined ? { payload } : {}),
    });
    if (response.statusCode >= 400) {
      throw new Error(`${method} ${url} failed (${response.statusCode}): ${response.body}`);
    }
    return response;
  }

  async function createProperty(name: string, rentableArea: string): Promise<string> {
    const response = await request('POST', '/api/v1/properties', owner.cookie, {
      name,
      propertyType: 'office',
      rentableArea,
    });
    return (response.json() as { property: { id: string } }).property.id;
  }

  async function addSpace(propertyId: string, code: string, area: string): Promise<void> {
    await request('PUT', `/api/v1/properties/${propertyId}/spaces`, owner.cookie, {
      spaces: [{ code, spaceType: 'office', area }],
    });
  }

  async function createModel(propertyId: string): Promise<string> {
    const response = await request('POST', '/api/v1/models', owner.cookie, {
      propertyId,
      name: 'Base case',
      classification: 'valuation',
      valuationDate: '2026-01-01',
      forecastStartDate: '2026-01-01',
      forecastMonths: 24,
      discountRate: '0.08',
      terminalCapRate: '0.07',
      saleMonth: 24,
    });
    return (response.json() as { model: { id: string } }).model.id;
  }

  async function addLease(
    modelId: string,
    code: string,
    tenantId: string,
    area: string,
    spaceCode: string,
    dates: { commencementDate: string; expirationDate: string; baseRent: string },
    marketLeasingProfileId?: string,
  ): Promise<void> {
    await request('PUT', `/api/v1/models/${modelId}/leases/${code}`, owner.cookie, {
      tenantId,
      status: 'occupied',
      area,
      spaceIds: [spaceCode],
      commencementDate: dates.commencementDate,
      expirationDate: dates.expirationDate,
      baseRent: dates.baseRent,
      baseRentBasis: 'per_area_per_year',
      ...(marketLeasingProfileId ? { marketLeasingProfileId } : {}),
    });
  }

  async function calculateModel(modelId: string): Promise<void> {
    await request('POST', `/api/v1/models/${modelId}/calculate`, owner.cookie, {});
  }

  async function createPortfolio(name: string, propertyIds: string[]): Promise<string> {
    const response = await request('POST', '/api/v1/portfolios', owner.cookie, {
      name,
      propertyIds,
    });
    return (response.json() as { portfolio: { id: string } }).portfolio.id;
  }

  interface TenantRow {
    tenantId: string;
    tenantName: string;
    annualBaseRent: string;
    occupiedArea: string;
    shareOfRent: string;
    shareOfArea: string;
    properties: Array<{ propertyId: string; propertyName: string }>;
    leaseCount: number;
    earliestExpiration: string | null;
  }
  interface ExposureBody {
    portfolio: { id: string; name: string };
    tenants: TenantRow[];
    totalAnnualBaseRent: string;
    totalOccupiedArea: string;
    propertyCount: number;
    excluded: Array<{ propertyId: string; propertyName: string; reason: string }>;
  }

  async function exposure(id = portfolioId): Promise<ExposureBody> {
    const response = await request('GET', `/api/v1/portfolios/${id}/tenant-exposure`, owner.cookie);
    return response.json() as ExposureBody;
  }

  /* ---------------------------------------------------------------------- */

  it('rolls one tenant’s exposure up across two properties', async () => {
    const body = await exposure();
    expect(body.tenants).toHaveLength(1);
    const [kestrel] = body.tenants;
    expect(kestrel?.tenantId).toBe(anchorTenantId);
    expect(kestrel?.tenantName).toBe(anchorTenantName);

    // Neither property alone would report this: 50,000 sqft on one, 30,000 on
    // the other, and the number that matters is the 80,000 sqft sum.
    expect(Number(kestrel?.occupiedArea)).toBeCloseTo(80000, 2);
    expect(kestrel?.properties).toHaveLength(2);
    expect(kestrel?.leaseCount).toBe(2);

    // A single tenant across every included property is, trivially, 100% of
    // the portfolio's rent and area.
    expect(Number(kestrel?.shareOfRent)).toBeCloseTo(1, 6);
    expect(Number(kestrel?.shareOfArea)).toBeCloseTo(1, 6);
  });

  it('states an earliest expiration drawn from the real lease rows', async () => {
    const [kestrel] = (await exposure()).tenants;
    // Both leases expire 2035-12-31 in this fixture; the field exists to
    // report whichever is soonest when they differ, which the next test
    // exercises indirectly through a second, shorter-lived tenant.
    expect(kestrel?.earliestExpiration).toBe('2035-12-31');
  });

  it('is refused to a different organization', async () => {
    const stranger = await registerActor(
      ctx.app,
      'tenant-exposure-stranger@example.invalid',
      'Stranger',
    );
    await request('POST', '/api/v1/organizations', stranger.cookie, { name: 'Unrelated Holdings' });

    const response = await ctx.app.inject({
      method: 'GET',
      url: `/api/v1/portfolios/${portfolioId}/tenant-exposure`,
      headers: authed(stranger.cookie),
    });
    expect(response.statusCode).toBe(404);
  });

  /* ---------------------------------------------------------------------- */

  describe('when a lease rolls over', () => {
    let rolloverPropertyId: string;
    let rolloverPortfolioId: string;
    let rolloverTenantId: string;

    beforeAll(async () => {
      rolloverPropertyId = await createProperty('Fennimore Rollover Wing', '10000');
      await addSpace(rolloverPropertyId, 'WHOLE', '10000');

      const modelId = await createModel(rolloverPropertyId);

      // Renewal probability well short of certain, so the forecast produces
      // both a `renewal` branch (the real tenant staying) and a `new_lease`
      // branch (the engine's placeholder for whoever fills the space if they
      // do not) — the two cases this whole feature has to tell apart.
      const profile = await request(
        'PUT',
        `/api/v1/models/${modelId}/market-leasing/MLP-1`,
        owner.cookie,
        {
          name: 'Office standard',
          marketRent: '28.00',
          marketRentBasis: 'per_area_per_year',
          renewalProbability: '0.5',
          downtimeMonths: 2,
          /*
           * Short enough that the `new_lease` branch's own hypothetical term
           * also expires inside this fixture's 24-month forecast, which
           * triggers a *second* round of rollover simulation on top of the
           * first. That nested branch is where the real defect lived: it
           * inherits `scenario: 'renewal'` from its speculative parent while
           * its tenant id stays the same synthetic placeholder, which is
           * exactly the case `scenario` alone cannot tell apart from a real
           * tenant renewing.
           */
          newLeaseTermMonths: 6,
        },
      );
      const profileId = (profile.json() as { item: { id: string } }).item.id;

      const tenant = await request('POST', '/api/v1/tenants', owner.cookie, {
        name: 'Winslow Design Studio',
      });
      rolloverTenantId = (tenant.json() as { tenant: { id: string } }).tenant.id;

      // Expires three months into a twenty-four month forecast, so the
      // rollover branches cover most of the year-1 window this endpoint sums.
      await addLease(
        modelId,
        'L-ROLL',
        rolloverTenantId,
        '10000',
        'WHOLE',
        { commencementDate: '2026-01-01', expirationDate: '2026-03-31', baseRent: '32.00' },
        profileId,
      );
      await calculateModel(modelId);

      rolloverPortfolioId = await createPortfolio('Fennimore Rollover Fund', [rolloverPropertyId]);
    }, 60_000);

    it('does not fail when the calculation includes a speculative rollover branch', async () => {
      // Before this was fixed, a `new_lease` row's synthetic tenant id
      // (`market:<profileId>`) reached a query that cast it to uuid, and the
      // request failed rather than excluding the row.
      const response = await ctx.app.inject({
        method: 'GET',
        url: `/api/v1/portfolios/${rolloverPortfolioId}/tenant-exposure`,
        headers: authed(owner.cookie),
      });
      expect(response.statusCode, response.body).toBe(200);
    });

    it('keeps the real tenant’s renewal exposure and drops the speculative fill', async () => {
      const body = await exposure(rolloverPortfolioId);

      const real = body.tenants.find((entry) => entry.tenantId === rolloverTenantId);
      expect(real).toBeDefined();
      expect(real?.tenantName).toBe('Winslow Design Studio');

      /*
       * The three contract months alone (Jan-Mar, $32.00/sqft/year on 10,000
       * sqft) would be $80,000. If the `renewal` branch were being dropped
       * along with `new_lease` — which is what excluding every non-"contract"
       * scenario would do — this is exactly what the total would still equal,
       * and the test above ("greater than 0") would not have noticed. Asserting
       * a total clearly above that figure is what actually distinguishes
       * "renewal counted" from "renewal dropped".
       */
      const contractOnly = 32 * 10000 * (3 / 12);
      expect(Number(real?.annualBaseRent)).toBeGreaterThan(contractOnly * 1.1);

      // No row for the engine's own placeholder — neither by the name
      // `leases.ts` gives it, nor as a second tenant at all.
      expect(body.tenants.some((entry) => entry.tenantName.includes('Market tenant'))).toBe(false);
      expect(body.tenants).toHaveLength(1);
    });
  });
});
