import { createHash, randomUUID } from 'node:crypto';
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, resolve, sep } from 'node:path';
import type { Env } from './env.js';

/**
 * Object storage for uploaded documents.
 *
 * Pluggable for the same reason `MAIL_DRIVER` and `SCAN_DRIVER` are: this
 * platform bundles no paid service. `LocalStorage` (`STORAGE_DRIVER=local`,
 * the default) writes to a directory on disk — free, and enough for a
 * single-node deployment or the docker-compose stack's own volume.
 * `STORAGE_DRIVER=s3` names the interface a real object store would
 * implement, but nothing implements it yet; `loadEnv` refuses to start with
 * it set, rather than accepting the setting and failing the first upload.
 *
 * `documents.storage_key` is opaque to every caller above this module — a
 * route never builds a filesystem path itself, so there is exactly one
 * place a path-traversal upload name could matter, and it is guarded here.
 */
export interface StoredFile {
  storageKey: string;
  storageDriver: string;
  byteSize: number;
  checksumSha256: string;
}

export interface Storage {
  readonly driver: string;
  save(organizationId: string, buffer: Buffer): Promise<StoredFile>;
  read(storageKey: string): Promise<Buffer>;
  remove(storageKey: string): Promise<void>;
}

export class LocalStorage implements Storage {
  readonly driver = 'local';

  constructor(private readonly root: string) {}

  async save(organizationId: string, buffer: Buffer): Promise<StoredFile> {
    // Namespaced by organization so a directory listing of the store on disk
    // already reflects the same boundary every query in this platform
    // enforces — not a substitute for that enforcement, just consistent
    // with it.
    const storageKey = `${organizationId}/${randomUUID()}`;
    const path = this.resolvePath(storageKey);
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, buffer);
    return {
      storageKey,
      storageDriver: this.driver,
      byteSize: buffer.byteLength,
      checksumSha256: createHash('sha256').update(buffer).digest('hex'),
    };
  }

  async read(storageKey: string): Promise<Buffer> {
    return readFile(this.resolvePath(storageKey));
  }

  async remove(storageKey: string): Promise<void> {
    await rm(this.resolvePath(storageKey), { force: true });
  }

  /**
   * `storageKey` is generated by `save` itself, never taken from a caller —
   * but a key read back out of the database is still an external input to
   * this function, so it is resolved the same defensive way regardless.
   */
  private resolvePath(storageKey: string): string {
    const root = resolve(this.root);
    const path = resolve(root, storageKey);
    if (path !== root && !path.startsWith(root + sep)) {
      throw new Error('Refused to resolve a storage key outside the storage root.');
    }
    return path;
  }
}

export function createStorage(env: Env): Storage {
  return new LocalStorage(env.STORAGE_LOCAL_DIR);
}
