import { buildServer } from '../apps/api/src/server.js';
import { loadEnv } from '../apps/api/src/env.js';

/**
 * Prints the API surface, as the router actually holds it.
 *
 * The repository had no generated API documentation and a hand-written list
 * would have been wrong within a release — which is the same failure the
 * documentation-count gate exists to stop. This asks the server instead, so the
 * answer cannot drift from the code by construction.
 *
 * It is not an OpenAPI document and does not pretend to be one. Request and
 * response shapes are validated by `zod` schemas declared inside each handler
 * rather than registered with Fastify, so nothing here can see them; emitting a
 * spec with empty schemas would look like a contract and describe nothing.
 * Producing a real one means lifting those schemas to the route definitions,
 * which is a change to every route and a decision rather than a script.
 *
 * What this does answer is the question a security review actually opens with:
 * what is exposed, and what can be reached without signing in.
 *
 *   pnpm api:inventory
 *   pnpm exec tsx scripts/api-inventory.ts --markdown > docs/api-surface.md
 *
 * Written with `pnpm exec` rather than `pnpm run` because `pnpm run` prints its
 * own banner to stdout, which lands in the middle of the generated document.
 */

/** Kept in step with `tests/route-inventory.test.ts`, which enforces it. */
const PUBLIC = new Set([
  'OPTIONS *',
  'GET /api/v1/health',
  'POST /api/v1/auth/register',
  'POST /api/v1/auth/login',
  'POST /api/v1/auth/logout',
  'POST /api/v1/auth/password-reset/request',
  'POST /api/v1/auth/password-reset/confirm',
]);

const ORDER = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'];

async function main(): Promise<void> {
  const markdown = process.argv.includes('--markdown');

  /*
   * A server is built but never listened on, and no database is touched: the
   * inventory is collected by Fastify's `onRoute` hook as routes register, long
   * before any handler could run. The connection string only has to parse.
   */
  const app = await buildServer({
    env: loadEnv({
      ...process.env,
      NODE_ENV: 'test',
      DATABASE_URL: process.env.DATABASE_URL ?? 'postgres://unused:unused@127.0.0.1:5432/unused',
      SESSION_SECRET:
        process.env.SESSION_SECRET ?? 'inventory-only-secret-long-enough-for-the-validator',
    }),
    logger: false,
  });

  const routes = [...app.routeInventory].sort(
    (a, b) => a.url.localeCompare(b.url) || ORDER.indexOf(a.method) - ORDER.indexOf(b.method),
  );

  const grouped = new Map<string, typeof routes>();
  for (const route of routes) {
    // Grouped by the first path segment after the version prefix, which is how
    // somebody reading this looks for an endpoint.
    const group = route.url.replace(/^\/api\/v1\//, '').split('/')[0] ?? 'root';
    const bucket = grouped.get(group) ?? [];
    bucket.push(route);
    grouped.set(group, bucket);
  }

  const publicCount = routes.filter((route) => PUBLIC.has(`${route.method} ${route.url}`)).length;

  if (markdown) {
    // `process.stdout.write` rather than `console.log`: this branch emits a
    // document meant to be redirected to a file, and the lint rule that permits
    // only warn and error is right about the rest of the codebase — those go to
    // stderr, which is exactly where a document must not go.
    const out = (line: string) => process.stdout.write(`${line}\n`);
    out('# API surface\n');
    out(
      'Generated by `pnpm api:inventory --markdown`. Do not edit by hand — it is the\n' +
        "router's own route table, printed. Every route not marked public refuses an\n" +
        'unauthenticated request, which `tests/route-inventory.test.ts` enforces for\n' +
        'every route rather than for a chosen few.\n',
    );
    out(`${routes.length} routes, of which ${publicCount} are reachable without a session.\n`);
    for (const [group, entries] of [...grouped].sort(([a], [b]) => a.localeCompare(b))) {
      out(`## ${group}\n`);
      out('| Method | Path | Session required |');
      out('| --- | --- | --- |');
      for (const route of entries) {
        const isPublic = PUBLIC.has(`${route.method} ${route.url}`);
        out(`| ${route.method} | \`${route.url}\` | ${isPublic ? 'No' : 'Yes'} |`);
      }
      out('');
    }
  } else {
    console.warn(`\n${routes.length} routes (${publicCount} public)\n`);
    for (const [group, entries] of [...grouped].sort(([a], [b]) => a.localeCompare(b))) {
      console.warn(`${group}`);
      for (const route of entries) {
        const isPublic = PUBLIC.has(`${route.method} ${route.url}`);
        console.warn(`  ${route.method.padEnd(6)} ${route.url}${isPublic ? '   (public)' : ''}`);
      }
      console.warn('');
    }
  }

  await app.close();
}

await main();
